{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack54 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Action_history_colour_mr where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Action_history_colour_mr =
    Record (HCons (LVPair Id (Expr (Maybe Int)))
            (HCons (LVPair History_name (Expr (Maybe String)))
             (HCons (LVPair Allegiance (Expr (Maybe String)))
              (HCons (LVPair X (Expr (Maybe Int)))
               (HCons (LVPair Y (Expr (Maybe Int)))
                (HCons (LVPair Tx (Expr (Maybe Int)))
                 (HCons (LVPair Ty (Expr (Maybe Int)))
                  (HCons (LVPair Ptype (Expr (Maybe String)))
                   (HCons (LVPair Tag (Expr (Maybe Int)))
                    (HCons (LVPair Spell_name (Expr (Maybe String)))
                     (HCons (LVPair Num_wizards (Expr (Maybe Int)))
                      (HCons (LVPair Turn_number (Expr (Maybe Int)))
                       (HCons (LVPair Turn_phase (Expr (Maybe String)))
                        (HCons (LVPair Colour (Expr (Maybe String))) HNil))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
action_history_colour_mr :: Table Action_history_colour_mr
action_history_colour_mr = baseTable "action_history_colour_mr"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Id Field
---------------------------------------------------------------------------

data IdTag
type Id = Proxy IdTag
instance ShowLabel Id where showLabel _ = "id"

xid :: Id
xid = proxy

---------------------------------------------------------------------------
-- History_name Field
---------------------------------------------------------------------------

data History_nameTag
type History_name = Proxy History_nameTag
instance ShowLabel History_name where showLabel _ = "history_name"

history_name :: History_name
history_name = proxy

---------------------------------------------------------------------------
-- Allegiance Field
---------------------------------------------------------------------------

data AllegianceTag
type Allegiance = Proxy AllegianceTag
instance ShowLabel Allegiance where showLabel _ = "allegiance"

allegiance :: Allegiance
allegiance = proxy

---------------------------------------------------------------------------
-- X Field
---------------------------------------------------------------------------

data XTag
type X = Proxy XTag
instance ShowLabel X where showLabel _ = "x"

x :: X
x = proxy

---------------------------------------------------------------------------
-- Y Field
---------------------------------------------------------------------------

data YTag
type Y = Proxy YTag
instance ShowLabel Y where showLabel _ = "y"

y :: Y
y = proxy

---------------------------------------------------------------------------
-- Tx Field
---------------------------------------------------------------------------

data TxTag
type Tx = Proxy TxTag
instance ShowLabel Tx where showLabel _ = "tx"

tx :: Tx
tx = proxy

---------------------------------------------------------------------------
-- Ty Field
---------------------------------------------------------------------------

data TyTag
type Ty = Proxy TyTag
instance ShowLabel Ty where showLabel _ = "ty"

ty :: Ty
ty = proxy

---------------------------------------------------------------------------
-- Ptype Field
---------------------------------------------------------------------------

data PtypeTag
type Ptype = Proxy PtypeTag
instance ShowLabel Ptype where showLabel _ = "ptype"

ptype :: Ptype
ptype = proxy

---------------------------------------------------------------------------
-- Tag Field
---------------------------------------------------------------------------

data TagTag
type Tag = Proxy TagTag
instance ShowLabel Tag where showLabel _ = "tag"

tag :: Tag
tag = proxy

---------------------------------------------------------------------------
-- Spell_name Field
---------------------------------------------------------------------------

data Spell_nameTag
type Spell_name = Proxy Spell_nameTag
instance ShowLabel Spell_name where showLabel _ = "spell_name"

spell_name :: Spell_name
spell_name = proxy

---------------------------------------------------------------------------
-- Num_wizards Field
---------------------------------------------------------------------------

data Num_wizardsTag
type Num_wizards = Proxy Num_wizardsTag
instance ShowLabel Num_wizards where showLabel _ = "num_wizards"

num_wizards :: Num_wizards
num_wizards = proxy

---------------------------------------------------------------------------
-- Turn_number Field
---------------------------------------------------------------------------

data Turn_numberTag
type Turn_number = Proxy Turn_numberTag
instance ShowLabel Turn_number where showLabel _ = "turn_number"

turn_number :: Turn_number
turn_number = proxy

---------------------------------------------------------------------------
-- Turn_phase Field
---------------------------------------------------------------------------

data Turn_phaseTag
type Turn_phase = Proxy Turn_phaseTag
instance ShowLabel Turn_phase where showLabel _ = "turn_phase"

turn_phase :: Turn_phase
turn_phase = proxy

---------------------------------------------------------------------------
-- Colour Field
---------------------------------------------------------------------------

data ColourTag
type Colour = Proxy ColourTag
instance ShowLabel Colour where showLabel _ = "colour"

colour :: Colour
colour = proxy
