{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack43 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.All_module_objects where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type All_module_objects =
    Record (HCons (LVPair Object_name (Expr (Maybe String)))
            (HCons (LVPair Object_type (Expr (Maybe String)))
             (HCons (LVPair Module_name (Expr (Maybe String))) HNil)))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
all_module_objects :: Table All_module_objects
all_module_objects = baseTable "all_module_objects"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Object_name Field
---------------------------------------------------------------------------

data Object_nameTag
type Object_name = Proxy Object_nameTag
instance ShowLabel Object_name where showLabel _ = "object_name"

object_name :: Object_name
object_name = proxy

---------------------------------------------------------------------------
-- Object_type Field
---------------------------------------------------------------------------

data Object_typeTag
type Object_type = Proxy Object_typeTag
instance ShowLabel Object_type where showLabel _ = "object_type"

object_type :: Object_type
object_type = proxy

---------------------------------------------------------------------------
-- Module_name Field
---------------------------------------------------------------------------

data Module_nameTag
type Module_name = Proxy Module_nameTag
instance ShowLabel Module_name where showLabel _ = "module_name"

module_name :: Module_name
module_name = proxy
