{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack42 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.All_database_objects where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type All_database_objects =
    Record (HCons (LVPair Object_type (Expr (Maybe String)))
            (HCons (LVPair Object_name (Expr (Maybe String))) HNil))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
all_database_objects :: Table All_database_objects
all_database_objects = baseTable "all_database_objects"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Object_type Field
---------------------------------------------------------------------------

data Object_typeTag
type Object_type = Proxy Object_typeTag
instance ShowLabel Object_type where showLabel _ = "object_type"

object_type :: Object_type
object_type = proxy

---------------------------------------------------------------------------
-- Object_name Field
---------------------------------------------------------------------------

data Object_nameTag
type Object_name = Proxy Object_nameTag
instance ShowLabel Object_name where showLabel _ = "object_name"

object_name :: Object_name
object_name = proxy
