{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack42 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Base_relvar_key_attributes where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Base_relvar_key_attributes =
    Record (HCons (LVPair Constraint_name (Expr (Maybe String)))
            (HCons (LVPair Attribute_name (Expr (Maybe String))) HNil))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
base_relvar_key_attributes :: Table Base_relvar_key_attributes
base_relvar_key_attributes = baseTable "base_relvar_key_attributes"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Constraint_name Field
---------------------------------------------------------------------------

data Constraint_nameTag
type Constraint_name = Proxy Constraint_nameTag
instance ShowLabel Constraint_name where
    showLabel _ = "constraint_name"

constraint_name :: Constraint_name
constraint_name = proxy

---------------------------------------------------------------------------
-- Attribute_name Field
---------------------------------------------------------------------------

data Attribute_nameTag
type Attribute_name = Proxy Attribute_nameTag
instance ShowLabel Attribute_name where
    showLabel _ = "attribute_name"

attribute_name :: Attribute_name
attribute_name = proxy
