{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack42 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Base_relvar_keys where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Base_relvar_keys =
    Record (HCons (LVPair Constraint_name (Expr (Maybe String)))
            (HCons (LVPair Relvar_name (Expr (Maybe String))) HNil))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
base_relvar_keys :: Table Base_relvar_keys
base_relvar_keys = baseTable "base_relvar_keys"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Constraint_name Field
---------------------------------------------------------------------------

data Constraint_nameTag
type Constraint_name = Proxy Constraint_nameTag
instance ShowLabel Constraint_name where
    showLabel _ = "constraint_name"

constraint_name :: Constraint_name
constraint_name = proxy

---------------------------------------------------------------------------
-- Relvar_name Field
---------------------------------------------------------------------------

data Relvar_nameTag
type Relvar_name = Proxy Relvar_nameTag
instance ShowLabel Relvar_name where showLabel _ = "relvar_name"

relvar_name :: Relvar_name
relvar_name = proxy
