{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack45 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Board_ranges where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Board_ranges =
    Record (HCons (LVPair X (Expr (Maybe Int)))
            (HCons (LVPair Y (Expr (Maybe Int)))
             (HCons (LVPair Range (Expr (Maybe Int)))
              (HCons (LVPair Tx (Expr (Maybe Int)))
               (HCons (LVPair Ty (Expr (Maybe Int))) HNil)))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
board_ranges :: Table Board_ranges
board_ranges = baseTable "board_ranges"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- X Field
---------------------------------------------------------------------------

data XTag
type X = Proxy XTag
instance ShowLabel X where showLabel _ = "x"

x :: X
x = proxy

---------------------------------------------------------------------------
-- Y Field
---------------------------------------------------------------------------

data YTag
type Y = Proxy YTag
instance ShowLabel Y where showLabel _ = "y"

y :: Y
y = proxy

---------------------------------------------------------------------------
-- Range Field
---------------------------------------------------------------------------

data RangeTag
type Range = Proxy RangeTag
instance ShowLabel Range where showLabel _ = "range"

range :: Range
range = proxy

---------------------------------------------------------------------------
-- Tx Field
---------------------------------------------------------------------------

data TxTag
type Tx = Proxy TxTag
instance ShowLabel Tx where showLabel _ = "tx"

tx :: Tx
tx = proxy

---------------------------------------------------------------------------
-- Ty Field
---------------------------------------------------------------------------

data TyTag
type Ty = Proxy TyTag
instance ShowLabel Ty where showLabel _ = "ty"

ty :: Ty
ty = proxy
