{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack44 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Board_sound_effects where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Board_sound_effects =
    Record (HCons (LVPair Id (Expr Int))
            (HCons (LVPair Subtype (Expr String))
             (HCons (LVPair Sound_name (Expr String))
              (HCons (LVPair Queuepos (Expr Int)) HNil))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
board_sound_effects :: Table Board_sound_effects
board_sound_effects = baseTable "board_sound_effects"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Id Field
---------------------------------------------------------------------------

data IdTag
type Id = Proxy IdTag
instance ShowLabel Id where showLabel _ = "id"

xid :: Id
xid = proxy

---------------------------------------------------------------------------
-- Subtype Field
---------------------------------------------------------------------------

data SubtypeTag
type Subtype = Proxy SubtypeTag
instance ShowLabel Subtype where showLabel _ = "subtype"

subtype :: Subtype
subtype = proxy

---------------------------------------------------------------------------
-- Sound_name Field
---------------------------------------------------------------------------

data Sound_nameTag
type Sound_name = Proxy Sound_nameTag
instance ShowLabel Sound_name where showLabel _ = "sound_name"

sound_name :: Sound_name
sound_name = proxy

---------------------------------------------------------------------------
-- Queuepos Field
---------------------------------------------------------------------------

data QueueposTag
type Queuepos = Proxy QueueposTag
instance ShowLabel Queuepos where showLabel _ = "queuepos"

queuepos :: Queuepos
queuepos = proxy
