{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack41 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Cast_success_checked_table where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Cast_success_checked_table =
    Record (HCons (LVPair Cast_success_checked (Expr Bool)) HNil)

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
cast_success_checked_table :: Table Cast_success_checked_table
cast_success_checked_table = baseTable "cast_success_checked_table"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Cast_success_checked Field
---------------------------------------------------------------------------

data Cast_success_checkedTag
type Cast_success_checked = Proxy Cast_success_checkedTag
instance ShowLabel Cast_success_checked where
    showLabel _ = "cast_success_checked"

cast_success_checked :: Cast_success_checked
cast_success_checked = proxy
