{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack41 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Client_valid_activate_actions where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Client_valid_activate_actions =
    Record (HCons (LVPair Action (Expr (Maybe String))) HNil)

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
client_valid_activate_actions :: Table
    Client_valid_activate_actions
client_valid_activate_actions = baseTable "client_valid_activate_actions"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Action Field
---------------------------------------------------------------------------

data ActionTag
type Action = Proxy ActionTag
instance ShowLabel Action where showLabel _ = "action"

action :: Action
action = proxy
