{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack44 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Colours where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Colours =
    Record (HCons (LVPair Name (Expr String))
            (HCons (LVPair Red (Expr Int))
             (HCons (LVPair Green (Expr Int))
              (HCons (LVPair Blue (Expr Int)) HNil))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
colours :: Table Colours
colours = baseTable "colours"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Name Field
---------------------------------------------------------------------------

data NameTag
type Name = Proxy NameTag
instance ShowLabel Name where showLabel _ = "name"

name :: Name
name = proxy

---------------------------------------------------------------------------
-- Red Field
---------------------------------------------------------------------------

data RedTag
type Red = Proxy RedTag
instance ShowLabel Red where showLabel _ = "red"

red :: Red
red = proxy

---------------------------------------------------------------------------
-- Green Field
---------------------------------------------------------------------------

data GreenTag
type Green = Proxy GreenTag
instance ShowLabel Green where showLabel _ = "green"

green :: Green
green = proxy

---------------------------------------------------------------------------
-- Blue Field
---------------------------------------------------------------------------

data BlueTag
type Blue = Proxy BlueTag
instance ShowLabel Blue where showLabel _ = "blue"

blue :: Blue
blue = proxy
