{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack41 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Creating_new_game_table where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Creating_new_game_table =
    Record (HCons (LVPair Creating_new_game (Expr Bool)) HNil)

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
creating_new_game_table :: Table Creating_new_game_table
creating_new_game_table = baseTable "creating_new_game_table"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Creating_new_game Field
---------------------------------------------------------------------------

data Creating_new_gameTag
type Creating_new_game = Proxy Creating_new_gameTag
instance ShowLabel Creating_new_game where
    showLabel _ = "creating_new_game"

creating_new_game :: Creating_new_game
creating_new_game = proxy
