{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack41 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Current_wizard_table where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Current_wizard_table =
    Record (HCons (LVPair Current_wizard (Expr String)) HNil)

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
current_wizard_table :: Table Current_wizard_table
current_wizard_table = baseTable "current_wizard_table"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Current_wizard Field
---------------------------------------------------------------------------

data Current_wizardTag
type Current_wizard = Proxy Current_wizardTag
instance ShowLabel Current_wizard where
    showLabel _ = "current_wizard"

current_wizard :: Current_wizard
current_wizard = proxy
