{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack42 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Current_wizard_spell_counts where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Current_wizard_spell_counts =
    Record (HCons (LVPair Spell_name (Expr (Maybe String)))
            (HCons (LVPair Count (Expr (Maybe Int))) HNil))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
current_wizard_spell_counts :: Table Current_wizard_spell_counts
current_wizard_spell_counts = baseTable "current_wizard_spell_counts"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Spell_name Field
---------------------------------------------------------------------------

data Spell_nameTag
type Spell_name = Proxy Spell_nameTag
instance ShowLabel Spell_name where showLabel _ = "spell_name"

spell_name :: Spell_name
spell_name = proxy

---------------------------------------------------------------------------
-- Count Field
---------------------------------------------------------------------------

data CountTag
type Count = Proxy CountTag
instance ShowLabel Count where showLabel _ = "count"

count :: Count
count = proxy
