{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack45 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Current_board_sound_effects where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Current_board_sound_effects =
    Record (HCons (LVPair Queuepos (Expr (Maybe Int)))
            (HCons (LVPair Id (Expr (Maybe Int)))
             (HCons (LVPair Subtype (Expr (Maybe String)))
              (HCons (LVPair Sound_name (Expr (Maybe String)))
               (HCons (LVPair Ticks (Expr (Maybe Int))) HNil)))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
current_board_sound_effects :: Table Current_board_sound_effects
current_board_sound_effects = baseTable "current_board_sound_effects"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Queuepos Field
---------------------------------------------------------------------------

data QueueposTag
type Queuepos = Proxy QueueposTag
instance ShowLabel Queuepos where showLabel _ = "queuepos"

queuepos :: Queuepos
queuepos = proxy

---------------------------------------------------------------------------
-- Id Field
---------------------------------------------------------------------------

data IdTag
type Id = Proxy IdTag
instance ShowLabel Id where showLabel _ = "id"

xid :: Id
xid = proxy

---------------------------------------------------------------------------
-- Subtype Field
---------------------------------------------------------------------------

data SubtypeTag
type Subtype = Proxy SubtypeTag
instance ShowLabel Subtype where showLabel _ = "subtype"

subtype :: Subtype
subtype = proxy

---------------------------------------------------------------------------
-- Sound_name Field
---------------------------------------------------------------------------

data Sound_nameTag
type Sound_name = Proxy Sound_nameTag
instance ShowLabel Sound_name where showLabel _ = "sound_name"

sound_name :: Sound_name
sound_name = proxy

---------------------------------------------------------------------------
-- Ticks Field
---------------------------------------------------------------------------

data TicksTag
type Ticks = Proxy TicksTag
instance ShowLabel Ticks where showLabel _ = "ticks"

ticks :: Ticks
ticks = proxy
