{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack42 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Database_constraints where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Database_constraints =
    Record (HCons (LVPair Constraint_name (Expr String))
            (HCons (LVPair Expression (Expr String)) HNil))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
database_constraints :: Table Database_constraints
database_constraints = baseTable "database_constraints"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Constraint_name Field
---------------------------------------------------------------------------

data Constraint_nameTag
type Constraint_name = Proxy Constraint_nameTag
instance ShowLabel Constraint_name where
    showLabel _ = "constraint_name"

constraint_name :: Constraint_name
constraint_name = proxy

---------------------------------------------------------------------------
-- Expression Field
---------------------------------------------------------------------------

data ExpressionTag
type Expression = Proxy ExpressionTag
instance ShowLabel Expression where showLabel _ = "expression"

expression :: Expression
expression = proxy
