{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack41 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Disable_spreading_table where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Disable_spreading_table =
    Record (HCons (LVPair Disable_spreading (Expr Bool)) HNil)

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
disable_spreading_table :: Table Disable_spreading_table
disable_spreading_table = baseTable "disable_spreading_table"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Disable_spreading Field
---------------------------------------------------------------------------

data Disable_spreadingTag
type Disable_spreading = Proxy Disable_spreadingTag
instance ShowLabel Disable_spreading where
    showLabel _ = "disable_spreading"

disable_spreading :: Disable_spreading
disable_spreading = proxy
