{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack41 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Game_completed_table where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Game_completed_table =
    Record (HCons (LVPair Game_completed (Expr Bool)) HNil)

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
game_completed_table :: Table Game_completed_table
game_completed_table = baseTable "game_completed_table"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Game_completed Field
---------------------------------------------------------------------------

data Game_completedTag
type Game_completed = Proxy Game_completedTag
instance ShowLabel Game_completed where
    showLabel _ = "game_completed"

game_completed :: Game_completed
game_completed = proxy
