{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack41 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.In_next_phase_hack_table where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type In_next_phase_hack_table =
    Record (HCons (LVPair In_next_phase_hack (Expr Bool)) HNil)

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
in_next_phase_hack_table :: Table In_next_phase_hack_table
in_next_phase_hack_table = baseTable "in_next_phase_hack_table"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- In_next_phase_hack Field
---------------------------------------------------------------------------

data In_next_phase_hackTag
type In_next_phase_hack = Proxy In_next_phase_hackTag
instance ShowLabel In_next_phase_hack where
    showLabel _ = "in_next_phase_hack"

in_next_phase_hack :: In_next_phase_hack
in_next_phase_hack = proxy
