{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack42 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Key_control_settings where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Key_control_settings =
    Record (HCons (LVPair Key_code (Expr String))
            (HCons (LVPair Action_name (Expr String)) HNil))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
key_control_settings :: Table Key_control_settings
key_control_settings = baseTable "key_control_settings"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Key_code Field
---------------------------------------------------------------------------

data Key_codeTag
type Key_code = Proxy Key_codeTag
instance ShowLabel Key_code where showLabel _ = "key_code"

key_code :: Key_code
key_code = proxy

---------------------------------------------------------------------------
-- Action_name Field
---------------------------------------------------------------------------

data Action_nameTag
type Action_name = Proxy Action_nameTag
instance ShowLabel Action_name where showLabel _ = "action_name"

action_name :: Action_name
action_name = proxy
