{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack41 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Last_history_effect_id_table where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Last_history_effect_id_table =
    Record (HCons (LVPair Last_history_effect_id (Expr Int)) HNil)

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
last_history_effect_id_table :: Table Last_history_effect_id_table
last_history_effect_id_table = baseTable "last_history_effect_id_table"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Last_history_effect_id Field
---------------------------------------------------------------------------

data Last_history_effect_idTag
type Last_history_effect_id = Proxy Last_history_effect_idTag
instance ShowLabel Last_history_effect_id where
    showLabel _ = "last_history_effect_id"

last_history_effect_id :: Last_history_effect_id
last_history_effect_id = proxy
