{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack52 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Live_wizards where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Live_wizards =
    Record (HCons (LVPair Wizard_name (Expr (Maybe String)))
            (HCons (LVPair Shadow_form (Expr (Maybe Bool)))
             (HCons (LVPair Magic_sword (Expr (Maybe Bool)))
              (HCons (LVPair Magic_knife (Expr (Maybe Bool)))
               (HCons (LVPair Magic_shield (Expr (Maybe Bool)))
                (HCons (LVPair Magic_wings (Expr (Maybe Bool)))
                 (HCons (LVPair Magic_armour (Expr (Maybe Bool)))
                  (HCons (LVPair Magic_bow (Expr (Maybe Bool)))
                   (HCons (LVPair Computer_controlled (Expr (Maybe Bool)))
                    (HCons (LVPair Original_place (Expr (Maybe Int)))
                     (HCons (LVPair Expired (Expr (Maybe Bool)))
                      (HCons (LVPair Place (Expr (Maybe Int))) HNil))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
live_wizards :: Table Live_wizards
live_wizards = baseTable "live_wizards"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Wizard_name Field
---------------------------------------------------------------------------

data Wizard_nameTag
type Wizard_name = Proxy Wizard_nameTag
instance ShowLabel Wizard_name where showLabel _ = "wizard_name"

wizard_name :: Wizard_name
wizard_name = proxy

---------------------------------------------------------------------------
-- Shadow_form Field
---------------------------------------------------------------------------

data Shadow_formTag
type Shadow_form = Proxy Shadow_formTag
instance ShowLabel Shadow_form where showLabel _ = "shadow_form"

shadow_form :: Shadow_form
shadow_form = proxy

---------------------------------------------------------------------------
-- Magic_sword Field
---------------------------------------------------------------------------

data Magic_swordTag
type Magic_sword = Proxy Magic_swordTag
instance ShowLabel Magic_sword where showLabel _ = "magic_sword"

magic_sword :: Magic_sword
magic_sword = proxy

---------------------------------------------------------------------------
-- Magic_knife Field
---------------------------------------------------------------------------

data Magic_knifeTag
type Magic_knife = Proxy Magic_knifeTag
instance ShowLabel Magic_knife where showLabel _ = "magic_knife"

magic_knife :: Magic_knife
magic_knife = proxy

---------------------------------------------------------------------------
-- Magic_shield Field
---------------------------------------------------------------------------

data Magic_shieldTag
type Magic_shield = Proxy Magic_shieldTag
instance ShowLabel Magic_shield where showLabel _ = "magic_shield"

magic_shield :: Magic_shield
magic_shield = proxy

---------------------------------------------------------------------------
-- Magic_wings Field
---------------------------------------------------------------------------

data Magic_wingsTag
type Magic_wings = Proxy Magic_wingsTag
instance ShowLabel Magic_wings where showLabel _ = "magic_wings"

magic_wings :: Magic_wings
magic_wings = proxy

---------------------------------------------------------------------------
-- Magic_armour Field
---------------------------------------------------------------------------

data Magic_armourTag
type Magic_armour = Proxy Magic_armourTag
instance ShowLabel Magic_armour where showLabel _ = "magic_armour"

magic_armour :: Magic_armour
magic_armour = proxy

---------------------------------------------------------------------------
-- Magic_bow Field
---------------------------------------------------------------------------

data Magic_bowTag
type Magic_bow = Proxy Magic_bowTag
instance ShowLabel Magic_bow where showLabel _ = "magic_bow"

magic_bow :: Magic_bow
magic_bow = proxy

---------------------------------------------------------------------------
-- Computer_controlled Field
---------------------------------------------------------------------------

data Computer_controlledTag
type Computer_controlled = Proxy Computer_controlledTag
instance ShowLabel Computer_controlled where
    showLabel _ = "computer_controlled"

computer_controlled :: Computer_controlled
computer_controlled = proxy

---------------------------------------------------------------------------
-- Original_place Field
---------------------------------------------------------------------------

data Original_placeTag
type Original_place = Proxy Original_placeTag
instance ShowLabel Original_place where
    showLabel _ = "original_place"

original_place :: Original_place
original_place = proxy

---------------------------------------------------------------------------
-- Expired Field
---------------------------------------------------------------------------

data ExpiredTag
type Expired = Proxy ExpiredTag
instance ShowLabel Expired where showLabel _ = "expired"

expired :: Expired
expired = proxy

---------------------------------------------------------------------------
-- Place Field
---------------------------------------------------------------------------

data PlaceTag
type Place = Proxy PlaceTag
instance ShowLabel Place where showLabel _ = "place"

place :: Place
place = proxy
