{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack42 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Modules where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Modules =
    Record (HCons (LVPair Module_name (Expr (Maybe String)))
            (HCons (LVPair Module_order (Expr Int)) HNil))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
modules :: Table Modules
modules = baseTable "modules"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Module_name Field
---------------------------------------------------------------------------

data Module_nameTag
type Module_name = Proxy Module_nameTag
instance ShowLabel Module_name where showLabel _ = "module_name"

module_name :: Module_name
module_name = proxy

---------------------------------------------------------------------------
-- Module_order Field
---------------------------------------------------------------------------

data Module_orderTag
type Module_order = Proxy Module_orderTag
instance ShowLabel Module_order where showLabel _ = "module_order"

module_order :: Module_order
module_order = proxy
