{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack42 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Next_wizard where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Next_wizard =
    Record (HCons (LVPair Wizard_name (Expr (Maybe String)))
            (HCons (LVPair New_wizard_name (Expr (Maybe String))) HNil))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
next_wizard :: Table Next_wizard
next_wizard = baseTable "next_wizard"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Wizard_name Field
---------------------------------------------------------------------------

data Wizard_nameTag
type Wizard_name = Proxy Wizard_nameTag
instance ShowLabel Wizard_name where showLabel _ = "wizard_name"

wizard_name :: Wizard_name
wizard_name = proxy

---------------------------------------------------------------------------
-- New_wizard_name Field
---------------------------------------------------------------------------

data New_wizard_nameTag
type New_wizard_name = Proxy New_wizard_nameTag
instance ShowLabel New_wizard_name where
    showLabel _ = "new_wizard_name"

new_wizard_name :: New_wizard_name
new_wizard_name = proxy
