{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack42 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Object_orders where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Object_orders =
    Record (HCons (LVPair Object_type (Expr (Maybe String)))
            (HCons (LVPair Object_order (Expr (Maybe Int))) HNil))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
object_orders :: Table Object_orders
object_orders = baseTable "object_orders"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Object_type Field
---------------------------------------------------------------------------

data Object_typeTag
type Object_type = Proxy Object_typeTag
instance ShowLabel Object_type where showLabel _ = "object_type"

object_type :: Object_type
object_type = proxy

---------------------------------------------------------------------------
-- Object_order Field
---------------------------------------------------------------------------

data Object_orderTag
type Object_order = Proxy Object_orderTag
instance ShowLabel Object_order where showLabel _ = "object_order"

object_order :: Object_order
object_order = proxy
