{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack42 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Operator_source where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Operator_source =
    Record (HCons (LVPair Operator_name (Expr (Maybe String)))
            (HCons (LVPair Source (Expr (Maybe String))) HNil))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
operator_source :: Table Operator_source
operator_source = baseTable "operator_source"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Operator_name Field
---------------------------------------------------------------------------

data Operator_nameTag
type Operator_name = Proxy Operator_nameTag
instance ShowLabel Operator_name where
    showLabel _ = "operator_name"

operator_name :: Operator_name
operator_name = proxy

---------------------------------------------------------------------------
-- Source Field
---------------------------------------------------------------------------

data SourceTag
type Source = Proxy SourceTag
instance ShowLabel Source where showLabel _ = "source"

source :: Source
source = proxy
