{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack44 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Piece_starting_ticks where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Piece_starting_ticks =
    Record (HCons (LVPair Ptype (Expr String))
            (HCons (LVPair Allegiance (Expr String))
             (HCons (LVPair Tag (Expr Int))
              (HCons (LVPair Start_tick (Expr Int)) HNil))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
piece_starting_ticks :: Table Piece_starting_ticks
piece_starting_ticks = baseTable "piece_starting_ticks"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Ptype Field
---------------------------------------------------------------------------

data PtypeTag
type Ptype = Proxy PtypeTag
instance ShowLabel Ptype where showLabel _ = "ptype"

ptype :: Ptype
ptype = proxy

---------------------------------------------------------------------------
-- Allegiance Field
---------------------------------------------------------------------------

data AllegianceTag
type Allegiance = Proxy AllegianceTag
instance ShowLabel Allegiance where showLabel _ = "allegiance"

allegiance :: Allegiance
allegiance = proxy

---------------------------------------------------------------------------
-- Tag Field
---------------------------------------------------------------------------

data TagTag
type Tag = Proxy TagTag
instance ShowLabel Tag where showLabel _ = "tag"

tag :: Tag
tag = proxy

---------------------------------------------------------------------------
-- Start_tick Field
---------------------------------------------------------------------------

data Start_tickTag
type Start_tick = Proxy Start_tickTag
instance ShowLabel Start_tick where showLabel _ = "start_tick"

start_tick :: Start_tick
start_tick = proxy
