{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack42 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Prompt where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Prompt =
    Record (HCons (LVPair Action (Expr (Maybe String)))
            (HCons (LVPair Help (Expr (Maybe String))) HNil))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
prompt :: Table Prompt
prompt = baseTable "prompt"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Action Field
---------------------------------------------------------------------------

data ActionTag
type Action = Proxy ActionTag
instance ShowLabel Action where showLabel _ = "action"

action :: Action
action = proxy

---------------------------------------------------------------------------
-- Help Field
---------------------------------------------------------------------------

data HelpTag
type Help = Proxy HelpTag
instance ShowLabel Help where showLabel _ = "help"

help :: Help
help = proxy
