{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack41 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Remaining_walk_table where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Remaining_walk_table =
    Record (HCons (LVPair Remaining_walk (Expr Int)) HNil)

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
remaining_walk_table :: Table Remaining_walk_table
remaining_walk_table = baseTable "remaining_walk_table"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Remaining_walk Field
---------------------------------------------------------------------------

data Remaining_walkTag
type Remaining_walk = Proxy Remaining_walkTag
instance ShowLabel Remaining_walk where
    showLabel _ = "remaining_walk"

remaining_walk :: Remaining_walk
remaining_walk = proxy
