{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack41 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Remaining_walk_hack_table where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Remaining_walk_hack_table =
    Record (HCons (LVPair Remaining_walk_hack (Expr Bool)) HNil)

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
remaining_walk_hack_table :: Table Remaining_walk_hack_table
remaining_walk_hack_table = baseTable "remaining_walk_hack_table"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Remaining_walk_hack Field
---------------------------------------------------------------------------

data Remaining_walk_hackTag
type Remaining_walk_hack = Proxy Remaining_walk_hackTag
instance ShowLabel Remaining_walk_hack where
    showLabel _ = "remaining_walk_hack"

remaining_walk_hack :: Remaining_walk_hack
remaining_walk_hack = proxy
