{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack41 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Scalars where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Scalars =
    Record (HCons (LVPair Scalar_name (Expr (Maybe String))) HNil)

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
scalars :: Table Scalars
scalars = baseTable "scalars"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Scalar_name Field
---------------------------------------------------------------------------

data Scalar_nameTag
type Scalar_name = Proxy Scalar_nameTag
instance ShowLabel Scalar_name where showLabel _ = "scalar_name"

scalar_name :: Scalar_name
scalar_name = proxy
