{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack42 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Section_orderv where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Section_orderv =
    Record (HCons (LVPair Section_order (Expr (Maybe Int)))
            (HCons (LVPair Spell_category (Expr (Maybe String))) HNil))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
section_orderv :: Table Section_orderv
section_orderv = baseTable "section_orderv"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Section_order Field
---------------------------------------------------------------------------

data Section_orderTag
type Section_order = Proxy Section_orderTag
instance ShowLabel Section_order where
    showLabel _ = "section_order"

section_order :: Section_order
section_order = proxy

---------------------------------------------------------------------------
-- Spell_category Field
---------------------------------------------------------------------------

data Spell_categoryTag
type Spell_category = Proxy Spell_categoryTag
instance ShowLabel Spell_category where
    showLabel _ = "spell_category"

spell_category :: Spell_category
spell_category = proxy
