{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack47 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Selected_piecexy where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Selected_piecexy =
    Record (HCons (LVPair Ptype (Expr (Maybe String)))
            (HCons (LVPair Allegiance (Expr (Maybe String)))
             (HCons (LVPair Tag (Expr (Maybe Int)))
              (HCons (LVPair Move_phase (Expr (Maybe String)))
               (HCons (LVPair Engaged (Expr (Maybe Bool)))
                (HCons (LVPair X (Expr (Maybe Int)))
                 (HCons (LVPair Y (Expr (Maybe Int))) HNil)))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
selected_piecexy :: Table Selected_piecexy
selected_piecexy = baseTable "selected_piecexy"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Ptype Field
---------------------------------------------------------------------------

data PtypeTag
type Ptype = Proxy PtypeTag
instance ShowLabel Ptype where showLabel _ = "ptype"

ptype :: Ptype
ptype = proxy

---------------------------------------------------------------------------
-- Allegiance Field
---------------------------------------------------------------------------

data AllegianceTag
type Allegiance = Proxy AllegianceTag
instance ShowLabel Allegiance where showLabel _ = "allegiance"

allegiance :: Allegiance
allegiance = proxy

---------------------------------------------------------------------------
-- Tag Field
---------------------------------------------------------------------------

data TagTag
type Tag = Proxy TagTag
instance ShowLabel Tag where showLabel _ = "tag"

tag :: Tag
tag = proxy

---------------------------------------------------------------------------
-- Move_phase Field
---------------------------------------------------------------------------

data Move_phaseTag
type Move_phase = Proxy Move_phaseTag
instance ShowLabel Move_phase where showLabel _ = "move_phase"

move_phase :: Move_phase
move_phase = proxy

---------------------------------------------------------------------------
-- Engaged Field
---------------------------------------------------------------------------

data EngagedTag
type Engaged = Proxy EngagedTag
instance ShowLabel Engaged where showLabel _ = "engaged"

engaged :: Engaged
engaged = proxy

---------------------------------------------------------------------------
-- X Field
---------------------------------------------------------------------------

data XTag
type X = Proxy XTag
instance ShowLabel X where showLabel _ = "x"

x :: X
x = proxy

---------------------------------------------------------------------------
-- Y Field
---------------------------------------------------------------------------

data YTag
type Y = Proxy YTag
instance ShowLabel Y where showLabel _ = "y"

y :: Y
y = proxy
