{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack41 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Spell_choice_hack_table where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Spell_choice_hack_table =
    Record (HCons (LVPair Spell_choice_hack (Expr Bool)) HNil)

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
spell_choice_hack_table :: Table Spell_choice_hack_table
spell_choice_hack_table = baseTable "spell_choice_hack_table"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Spell_choice_hack Field
---------------------------------------------------------------------------

data Spell_choice_hackTag
type Spell_choice_hack = Proxy Spell_choice_hackTag
instance ShowLabel Spell_choice_hack where
    showLabel _ = "spell_choice_hack"

spell_choice_hack :: Spell_choice_hack
spell_choice_hack = proxy
