{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack45 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Spells_mr_base where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Spells_mr_base =
    Record (HCons (LVPair Spell_name (Expr (Maybe String)))
            (HCons (LVPair Base_chance (Expr (Maybe Int)))
             (HCons (LVPair Alignment (Expr (Maybe Int)))
              (HCons (LVPair Spell_category (Expr (Maybe String)))
               (HCons (LVPair Description (Expr (Maybe String))) HNil)))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
spells_mr_base :: Table Spells_mr_base
spells_mr_base = baseTable "spells_mr_base"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Spell_name Field
---------------------------------------------------------------------------

data Spell_nameTag
type Spell_name = Proxy Spell_nameTag
instance ShowLabel Spell_name where showLabel _ = "spell_name"

spell_name :: Spell_name
spell_name = proxy

---------------------------------------------------------------------------
-- Base_chance Field
---------------------------------------------------------------------------

data Base_chanceTag
type Base_chance = Proxy Base_chanceTag
instance ShowLabel Base_chance where showLabel _ = "base_chance"

base_chance :: Base_chance
base_chance = proxy

---------------------------------------------------------------------------
-- Alignment Field
---------------------------------------------------------------------------

data AlignmentTag
type Alignment = Proxy AlignmentTag
instance ShowLabel Alignment where showLabel _ = "alignment"

alignment :: Alignment
alignment = proxy

---------------------------------------------------------------------------
-- Spell_category Field
---------------------------------------------------------------------------

data Spell_categoryTag
type Spell_category = Proxy Spell_categoryTag
instance ShowLabel Spell_category where
    showLabel _ = "spell_category"

spell_category :: Spell_category
spell_category = proxy

---------------------------------------------------------------------------
-- Description Field
---------------------------------------------------------------------------

data DescriptionTag
type Description = Proxy DescriptionTag
instance ShowLabel Description where showLabel _ = "description"

description :: Description
description = proxy
