{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack41 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Spell_parts_to_cast_table where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Spell_parts_to_cast_table =
    Record (HCons (LVPair Spell_parts_to_cast (Expr Int)) HNil)

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
spell_parts_to_cast_table :: Table Spell_parts_to_cast_table
spell_parts_to_cast_table = baseTable "spell_parts_to_cast_table"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Spell_parts_to_cast Field
---------------------------------------------------------------------------

data Spell_parts_to_castTag
type Spell_parts_to_cast = Proxy Spell_parts_to_castTag
instance ShowLabel Spell_parts_to_cast where
    showLabel _ = "spell_parts_to_cast"

spell_parts_to_cast :: Spell_parts_to_cast
spell_parts_to_cast = proxy
