{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack47 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Spells_with_order where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Spells_with_order =
    Record (HCons (LVPair Spell_category (Expr (Maybe String)))
            (HCons (LVPair Spell_name (Expr (Maybe String)))
             (HCons (LVPair Base_chance (Expr (Maybe Int)))
              (HCons (LVPair Alignment (Expr (Maybe Int)))
               (HCons (LVPair Description (Expr (Maybe String)))
                (HCons (LVPair Section_order (Expr (Maybe Int)))
                 (HCons (LVPair Alignment_order (Expr (Maybe Int))) HNil)))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
spells_with_order :: Table Spells_with_order
spells_with_order = baseTable "spells_with_order"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Spell_category Field
---------------------------------------------------------------------------

data Spell_categoryTag
type Spell_category = Proxy Spell_categoryTag
instance ShowLabel Spell_category where
    showLabel _ = "spell_category"

spell_category :: Spell_category
spell_category = proxy

---------------------------------------------------------------------------
-- Spell_name Field
---------------------------------------------------------------------------

data Spell_nameTag
type Spell_name = Proxy Spell_nameTag
instance ShowLabel Spell_name where showLabel _ = "spell_name"

spell_name :: Spell_name
spell_name = proxy

---------------------------------------------------------------------------
-- Base_chance Field
---------------------------------------------------------------------------

data Base_chanceTag
type Base_chance = Proxy Base_chanceTag
instance ShowLabel Base_chance where showLabel _ = "base_chance"

base_chance :: Base_chance
base_chance = proxy

---------------------------------------------------------------------------
-- Alignment Field
---------------------------------------------------------------------------

data AlignmentTag
type Alignment = Proxy AlignmentTag
instance ShowLabel Alignment where showLabel _ = "alignment"

alignment :: Alignment
alignment = proxy

---------------------------------------------------------------------------
-- Description Field
---------------------------------------------------------------------------

data DescriptionTag
type Description = Proxy DescriptionTag
instance ShowLabel Description where showLabel _ = "description"

description :: Description
description = proxy

---------------------------------------------------------------------------
-- Section_order Field
---------------------------------------------------------------------------

data Section_orderTag
type Section_order = Proxy Section_orderTag
instance ShowLabel Section_order where
    showLabel _ = "section_order"

section_order :: Section_order
section_order = proxy

---------------------------------------------------------------------------
-- Alignment_order Field
---------------------------------------------------------------------------

data Alignment_orderTag
type Alignment_order = Proxy Alignment_orderTag
instance ShowLabel Alignment_order where
    showLabel _ = "alignment_order"

alignment_order :: Alignment_order
alignment_order = proxy
