{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack42 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Spell_indexes_no_dis_turm where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Spell_indexes_no_dis_turm =
    Record (HCons (LVPair Row_number (Expr Int))
            (HCons (LVPair Spell_name (Expr String)) HNil))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
spell_indexes_no_dis_turm :: Table Spell_indexes_no_dis_turm
spell_indexes_no_dis_turm = baseTable "spell_indexes_no_dis_turm"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Row_number Field
---------------------------------------------------------------------------

data Row_numberTag
type Row_number = Proxy Row_numberTag
instance ShowLabel Row_number where showLabel _ = "row_number"

row_number :: Row_number
row_number = proxy

---------------------------------------------------------------------------
-- Spell_name Field
---------------------------------------------------------------------------

data Spell_nameTag
type Spell_name = Proxy Spell_nameTag
instance ShowLabel Spell_name where showLabel _ = "spell_name"

spell_name :: Spell_name
spell_name = proxy
