{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack42 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Test_action_overrides where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Test_action_overrides =
    Record (HCons (LVPair Override (Expr String))
            (HCons (LVPair Setting (Expr Bool)) HNil))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
test_action_overrides :: Table Test_action_overrides
test_action_overrides = baseTable "test_action_overrides"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Override Field
---------------------------------------------------------------------------

data OverrideTag
type Override = Proxy OverrideTag
instance ShowLabel Override where showLabel _ = "override"

override :: Override
override = proxy

---------------------------------------------------------------------------
-- Setting Field
---------------------------------------------------------------------------

data SettingTag
type Setting = Proxy SettingTag
instance ShowLabel Setting where showLabel _ = "setting"

setting :: Setting
setting = proxy
