{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack60 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Triggers where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Triggers =
    Record (HCons (LVPair Relvar_name (Expr (Maybe String)))
            (HCons (LVPair Trigger_catalog (Expr (Maybe String)))
             (HCons (LVPair Trigger_schema (Expr (Maybe String)))
              (HCons (LVPair Trigger_name (Expr (Maybe String)))
               (HCons (LVPair Trigger_name (Expr (Maybe String)))
                (HCons (LVPair Operator_name (Expr (Maybe String)))
                 (HCons (LVPair Event_manipulation (Expr (Maybe String)))
                  (HCons (LVPair Event_object_catalog (Expr (Maybe String)))
                   (HCons (LVPair Event_object_schema (Expr (Maybe String)))
                    (HCons (LVPair Event_object_table (Expr (Maybe String)))
                     (HCons (LVPair Action_order (Expr (Maybe String)))
                      (HCons (LVPair Action_condition (Expr (Maybe String)))
                       (HCons (LVPair Action_statement (Expr (Maybe String)))
                        (HCons (LVPair Action_orientation (Expr (Maybe String)))
                         (HCons (LVPair Condition_timing (Expr (Maybe String)))
                          (HCons (LVPair Condition_reference_old_table (Expr (Maybe String)))
                           (HCons (LVPair Condition_reference_new_table (Expr (Maybe String)))
                            (HCons (LVPair Condition_reference_old_row (Expr (Maybe String)))
                             (HCons (LVPair Condition_reference_new_row (Expr (Maybe String)))
                              (HCons (LVPair Created (Expr (Maybe String))) HNil))))))))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
triggers :: Table Triggers
triggers = baseTable "triggers"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Relvar_name Field
---------------------------------------------------------------------------

data Relvar_nameTag
type Relvar_name = Proxy Relvar_nameTag
instance ShowLabel Relvar_name where showLabel _ = "relvar_name"

relvar_name :: Relvar_name
relvar_name = proxy

---------------------------------------------------------------------------
-- Trigger_catalog Field
---------------------------------------------------------------------------

data Trigger_catalogTag
type Trigger_catalog = Proxy Trigger_catalogTag
instance ShowLabel Trigger_catalog where
    showLabel _ = "trigger_catalog"

trigger_catalog :: Trigger_catalog
trigger_catalog = proxy

---------------------------------------------------------------------------
-- Trigger_schema Field
---------------------------------------------------------------------------

data Trigger_schemaTag
type Trigger_schema = Proxy Trigger_schemaTag
instance ShowLabel Trigger_schema where
    showLabel _ = "trigger_schema"

trigger_schema :: Trigger_schema
trigger_schema = proxy

---------------------------------------------------------------------------
-- Trigger_name Field
---------------------------------------------------------------------------

data Trigger_nameTag
type Trigger_name = Proxy Trigger_nameTag
instance ShowLabel Trigger_name where showLabel _ = "trigger_name"

trigger_name :: Trigger_name
trigger_name = proxy

---------------------------------------------------------------------------
-- Trigger_name Field
---------------------------------------------------------------------------

data Trigger_nameTag
type Trigger_name = Proxy Trigger_nameTag
instance ShowLabel Trigger_name where showLabel _ = "trigger_name"

trigger_name :: Trigger_name
trigger_name = proxy

---------------------------------------------------------------------------
-- Operator_name Field
---------------------------------------------------------------------------

data Operator_nameTag
type Operator_name = Proxy Operator_nameTag
instance ShowLabel Operator_name where
    showLabel _ = "operator_name"

operator_name :: Operator_name
operator_name = proxy

---------------------------------------------------------------------------
-- Event_manipulation Field
---------------------------------------------------------------------------

data Event_manipulationTag
type Event_manipulation = Proxy Event_manipulationTag
instance ShowLabel Event_manipulation where
    showLabel _ = "event_manipulation"

event_manipulation :: Event_manipulation
event_manipulation = proxy

---------------------------------------------------------------------------
-- Event_object_catalog Field
---------------------------------------------------------------------------

data Event_object_catalogTag
type Event_object_catalog = Proxy Event_object_catalogTag
instance ShowLabel Event_object_catalog where
    showLabel _ = "event_object_catalog"

event_object_catalog :: Event_object_catalog
event_object_catalog = proxy

---------------------------------------------------------------------------
-- Event_object_schema Field
---------------------------------------------------------------------------

data Event_object_schemaTag
type Event_object_schema = Proxy Event_object_schemaTag
instance ShowLabel Event_object_schema where
    showLabel _ = "event_object_schema"

event_object_schema :: Event_object_schema
event_object_schema = proxy

---------------------------------------------------------------------------
-- Event_object_table Field
---------------------------------------------------------------------------

data Event_object_tableTag
type Event_object_table = Proxy Event_object_tableTag
instance ShowLabel Event_object_table where
    showLabel _ = "event_object_table"

event_object_table :: Event_object_table
event_object_table = proxy

---------------------------------------------------------------------------
-- Action_order Field
---------------------------------------------------------------------------

data Action_orderTag
type Action_order = Proxy Action_orderTag
instance ShowLabel Action_order where showLabel _ = "action_order"

action_order :: Action_order
action_order = proxy

---------------------------------------------------------------------------
-- Action_condition Field
---------------------------------------------------------------------------

data Action_conditionTag
type Action_condition = Proxy Action_conditionTag
instance ShowLabel Action_condition where
    showLabel _ = "action_condition"

action_condition :: Action_condition
action_condition = proxy

---------------------------------------------------------------------------
-- Action_statement Field
---------------------------------------------------------------------------

data Action_statementTag
type Action_statement = Proxy Action_statementTag
instance ShowLabel Action_statement where
    showLabel _ = "action_statement"

action_statement :: Action_statement
action_statement = proxy

---------------------------------------------------------------------------
-- Action_orientation Field
---------------------------------------------------------------------------

data Action_orientationTag
type Action_orientation = Proxy Action_orientationTag
instance ShowLabel Action_orientation where
    showLabel _ = "action_orientation"

action_orientation :: Action_orientation
action_orientation = proxy

---------------------------------------------------------------------------
-- Condition_timing Field
---------------------------------------------------------------------------

data Condition_timingTag
type Condition_timing = Proxy Condition_timingTag
instance ShowLabel Condition_timing where
    showLabel _ = "condition_timing"

condition_timing :: Condition_timing
condition_timing = proxy

---------------------------------------------------------------------------
-- Condition_reference_old_table Field
---------------------------------------------------------------------------

data Condition_reference_old_tableTag
type Condition_reference_old_table = Proxy Condition_reference_old_tableTag
instance ShowLabel Condition_reference_old_table where
    showLabel _ = "condition_reference_old_table"

condition_reference_old_table :: Condition_reference_old_table
condition_reference_old_table = proxy

---------------------------------------------------------------------------
-- Condition_reference_new_table Field
---------------------------------------------------------------------------

data Condition_reference_new_tableTag
type Condition_reference_new_table = Proxy Condition_reference_new_tableTag
instance ShowLabel Condition_reference_new_table where
    showLabel _ = "condition_reference_new_table"

condition_reference_new_table :: Condition_reference_new_table
condition_reference_new_table = proxy

---------------------------------------------------------------------------
-- Condition_reference_old_row Field
---------------------------------------------------------------------------

data Condition_reference_old_rowTag
type Condition_reference_old_row = Proxy Condition_reference_old_rowTag
instance ShowLabel Condition_reference_old_row where
    showLabel _ = "condition_reference_old_row"

condition_reference_old_row :: Condition_reference_old_row
condition_reference_old_row = proxy

---------------------------------------------------------------------------
-- Condition_reference_new_row Field
---------------------------------------------------------------------------

data Condition_reference_new_rowTag
type Condition_reference_new_row = Proxy Condition_reference_new_rowTag
instance ShowLabel Condition_reference_new_row where
    showLabel _ = "condition_reference_new_row"

condition_reference_new_row :: Condition_reference_new_row
condition_reference_new_row = proxy

---------------------------------------------------------------------------
-- Created Field
---------------------------------------------------------------------------

data CreatedTag
type Created = Proxy CreatedTag
instance ShowLabel Created where showLabel _ = "created"

created :: Created
created = proxy
