{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack41 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Turn_number_table where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Turn_number_table =
    Record (HCons (LVPair Turn_number (Expr Int)) HNil)

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
turn_number_table :: Table Turn_number_table
turn_number_table = baseTable "turn_number_table"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Turn_number Field
---------------------------------------------------------------------------

data Turn_numberTag
type Turn_number = Proxy Turn_numberTag
instance ShowLabel Turn_number where showLabel _ = "turn_number"

turn_number :: Turn_number
turn_number = proxy
