{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack41 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Turn_phase_table where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Turn_phase_table =
    Record (HCons (LVPair Turn_phase (Expr String)) HNil)

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
turn_phase_table :: Table Turn_phase_table
turn_phase_table = baseTable "turn_phase_table"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Turn_phase Field
---------------------------------------------------------------------------

data Turn_phaseTag
type Turn_phase = Proxy Turn_phaseTag
instance ShowLabel Turn_phase where showLabel _ = "turn_phase"

turn_phase :: Turn_phase
turn_phase = proxy
