{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack43 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.Wizard_display_info where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Wizard_display_info =
    Record (HCons (LVPair Wizard_name (Expr String))
            (HCons (LVPair Default_sprite (Expr String))
             (HCons (LVPair Colour (Expr String)) HNil)))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
wizard_display_info :: Table Wizard_display_info
wizard_display_info = baseTable "wizard_display_info"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Wizard_name Field
---------------------------------------------------------------------------

data Wizard_nameTag
type Wizard_name = Proxy Wizard_nameTag
instance ShowLabel Wizard_name where showLabel _ = "wizard_name"

wizard_name :: Wizard_name
wizard_name = proxy

---------------------------------------------------------------------------
-- Default_sprite Field
---------------------------------------------------------------------------

data Default_spriteTag
type Default_sprite = Proxy Default_spriteTag
instance ShowLabel Default_sprite where
    showLabel _ = "default_sprite"

default_sprite :: Default_sprite
default_sprite = proxy

---------------------------------------------------------------------------
-- Colour Field
---------------------------------------------------------------------------

data ColourTag
type Colour = Proxy ColourTag
instance ShowLabel Colour where showLabel _ = "colour"

colour :: Colour
colour = proxy
