{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack41 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Games.Chaos2010.Database.World_alignment_table where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type World_alignment_table =
    Record (HCons (LVPair World_alignment (Expr Int)) HNil)

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
world_alignment_table :: Table World_alignment_table
world_alignment_table = baseTable "world_alignment_table"

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- World_alignment Field
---------------------------------------------------------------------------

data World_alignmentTag
type World_alignment = Proxy World_alignmentTag
instance ShowLabel World_alignment where
    showLabel _ = "world_alignment"

world_alignment :: World_alignment
world_alignment = proxy
